		window.songFileMap = {
			"yourNumberOne": {
				base: "yourNumberOne",
				display: "Your Number One",
				bouncesPerLine: 12,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 36,
				font: "Consolas",
				lyricsFile: "yourNumberOne.lyric",
				chords: "yourNumberOneChords_v1.jpg",
				credits: `Your Number One\nWritten by Chris Sullivan\nKathleen Johnson — vocals\nChris Sullivan — guitar\nGreg Jeeves — keyboards, engineering, recording\nRecorded Oxford Studio, Ottawa`,
				appointments: [
					{ time: 0.00, type: "jump", nextIndex: 99, reference: "beginning", fired: false },
					{ time: 7.02, type: "jump", nextIndex: 0,  reference: "Intro", fired: false },
					{ time: 11.88, type: "jump", nextIndex: 1,  reference: "Intro", fired: false },
					{ time: 14.14, type: "jump", nextIndex: 2,  reference: "Intro", fired: false },
					{ time: 18.35, type: "jump", nextIndex: 3,  reference: "I don't want to be the president", fired: false },
					{ time: 22.13, type: "jump", nextIndex: 4,  reference: "Without you by my side", fired: false },
					{ time: 25.01, type: "jump", nextIndex: 5,  reference: "And I don't want to get married", fired: false },
					{ time: 28.92, type: "jump", nextIndex: 6,  reference: "If I can't be your bride", fired: false },
					{ time: 32.38, type: "jump", nextIndex: 7,  reference: "If I'm elected I'll refuse to serve", fired: false },
					{ time: 35.63, type: "jump", nextIndex: 8,  reference: "Nominated I will not run", fired: false },
					{ time: 38.74, type: "jump", nextIndex: 9,  reference: "These days of glory - chorus 1", fired: false },
					{ time: 42.82, type: "jump", nextIndex: 10,  reference: "If I can't be your number one - chorus 1", fired: false },
					{ time: 47.45, type: "jump", nextIndex: 11,  reference: "Fill", fired: false },
					{ time: 51.26, type: "jump", nextIndex: 12,  reference: "I don't wanna get no olympic gold medals", fired: false },
					{ time: 54.52, type: "jump", nextIndex: 13, reference: "If you won't let me meddle with you", fired: false },
					{ time: 58.30, type: "jump", nextIndex: 14, reference: "And I don't wanna be no shipping magnate", fired: false },
					{ time: 61.36, type: "jump", nextIndex: 15, reference: "If you won't magnetize me too", fired: false },
					{ time: 64.78, type: "jump", nextIndex: 16, reference: "Without you for inspiration", fired: false },
					{ time: 68.07, type: "jump", nextIndex: 17, reference: "What no man has ever done", fired: false },
					{ time: 71.67, type: "jump", nextIndex: 18, reference: "These days of glory - chorus 2", fired: false },
					{ time: 75.26, type: "jump", nextIndex: 19, reference: "If I can't be your number one - chorus 2", fired: false },
					{ time: 80.13, type: "jump", nextIndex: 20, reference: "Fill", fired: false },
					{ time: 83.94, type: "jump", nextIndex: 21, reference: "I don't care about Nobel prizes", fired: false },
					{ time: 87.05, type: "jump", nextIndex: 22, reference: "If I can't ring no bells with you", fired: false },
					{ time: 90.49, type: "jump", nextIndex: 23, reference: "And I don't wanna keep my America's Cup", fired: false },
					{ time: 93.75, type: "jump", nextIndex: 24, reference: "If you won't let me be your crew", fired: false },
					{ time: 97.38, type: "jump", nextIndex: 25, reference: "I don't wanna play the finals", fired: false },
					{ time: 100.63, type: "jump", nextIndex: 26, reference: "And I'll forfeit at Wimbledon", fired: false },
					{ time: 104.06, type: "jump", nextIndex: 27, reference: "These days of glory - chorus 3", fired: false },
					{ time: 107.82, type: "jump", nextIndex: 28, reference: "If I can't be your number one - chorus 3", fired: false },
					{ time: 112.85, type: "jump", nextIndex: 29, reference: "Fill", fired: false },
					{ time: 116.66, type: "jump", nextIndex: 30, reference: "I don't wanna be on no Rolling Stone cover", fired: false },
					{ time: 119.51, type: "jump", nextIndex: 31, reference: "If you won't go undercover with me", fired: false },
					{ time: 123.20, type: "jump", nextIndex: 32, reference: "And if you won't let me spend it all on you", fired: false },
					{ time: 126.13, type: "jump", nextIndex: 33, reference: "Then I don't wanna win the lottery", fired: false },
					{ time: 130.27, type: "jump", nextIndex: 34, reference: "Mister Pulitzer you can mail it", fired: false },
					{ time: 133.33, type: "jump", nextIndex: 35, reference: "At her Post down in Washington", fired: false },
					{ time: 136.57, type: "jump", nextIndex: 36, reference: "These days of glory - chorus 4", fired: false },
					{ time: 140.35, type: "jump", nextIndex: 37, reference: "If I can't be your number one - chorus 4", fired: false },
					{ time: 142.51, type: "jump", nextIndex: 38, reference: "Fill", fired: false },
					{ time: 149.21, type: "jump", nextIndex: 39, reference: "I don't wanna climb Mount Everest", fired: false },
					{ time: 152.22, type: "jump", nextIndex: 40, reference: "If I can't ever rest with you", fired: false },
					{ time: 156.16, type: "jump", nextIndex: 41, reference: "I don't wanna end up in that Book of Records", fired: false },
					{ time: 158.70, type: "jump", nextIndex: 42, reference: "If I can't begin as your Who's Who", fired: false },
					{ time: 162.47, type: "jump", nextIndex: 43, reference: "I don't want them to put me in that Hall of Fame", fired: false },
					{ time: 166.08, type: "jump", nextIndex: 44, reference: "For all those games I won", fired: false },
					{ time: 169.32, type: "jump", nextIndex: 45, reference: "These days of glory - chorus 6", fired: false },
					{ time: 172.91, type: "jump", nextIndex: 46, reference: "If I can't be your number one - chorus 6", fired: false },
					{ time: 181.22, type: "jump", nextIndex: 47, reference: "These days of glory - chorus 7", fired: false },
					{ time: 184.97, type: "jump", nextIndex: 48, reference: "If I can't be your number one - chorus 6", fired: false },
					{ time: 187.31, type: "jump", nextIndex: 49, reference: "These days, days of glory", fired: false },
					{ time: 190.73, type: "jump", nextIndex: 50, reference: "These days, days of glory", fired: false },
					{ time: 193.25, type: "jump", nextIndex: 51, reference: "These days of glory - chorus 8", fired: false },
					{ time: 196.95, type: "jump", nextIndex: 52, reference: "If I can't be your number one - chorus 6", fired: false },
					{ time: 201.96, type: "jump", nextIndex: 53, reference: "If I can't be your number one - chorus 6", fired: false },
					{ time: 207.10, type: "Y1pause", nextIndex: 54, reference: "song ended", fired: false }
				]
			},
			"foreignAffair": {
				base: "aForeignAffair",
				display: "A Foreign Affair",
				bouncesPerLine: 8,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 32,
				font: "Consolas",
				lyricsFile: "aForeignAffair.lyric",
				chords: "aForeignAffairChords_v1.jpg",
				credits: `A Foreign Affair\nWritten by Tom Waits\nChris Sullivan — vocals, guitar\nKathleen Johnson — vocals (bridge)\nRecorded Ottawa`,		
				appointments: [
					{ time: 0.00,   type: "jump", nextIndex: 99,  reference: "beginning", fired: false },
					// { time: 1.00,   type: "jump", nextIndex: 1,  reference: "Intro", fired: false },
					{ time: 13.04,  type: "jump", nextIndex: 1,  reference: "When traveling abroad", fired: false },
					{ time: 19.28,  type: "jump", nextIndex: 2,  reference: "It's my belief", fired: false },
					{ time: 29.09,  type: "jump", nextIndex: 3,  reference: "And subsequently", fired: false },
					{ time: 35.37,  type: "jump", nextIndex: 4,  reference: "Allows you a perspective", fired: false },
					{ time: 41.84,  type: "jump", nextIndex: 5,  reference: "And though you'll find", fired: false },
					{ time: 48.92,  type: "jump", nextIndex: 6,  reference: "Your wanderlust", fired: false },
					{ time: 55.24,  type: "jump", nextIndex: 7,  reference: "And you'll wonder", fired: false },
					{ time: 61.21,  type: "jump", nextIndex: 8,  reference: "To stay within the city limits", fired: false },
					{ time: 69.46,  type: "jump", nextIndex: 9, reference: "Most vagabonds", fired: false },
					{ time: 76.97,  type: "jump", nextIndex: 10, reference: "That remains the object", fired: false },
					{ time: 83.85,  type: "jump", nextIndex: 11, reference: "The obsession's in the chasing", fired: false },
					{ time: 91.83,  type: "jump", nextIndex: 12, reference: "The pursuit you see", fired: false },
					{ time: 102.69, type: "jump", nextIndex: 13, reference: "Without fear of contradiction", fired: false },
					{ time: 108.86, type: "jump", nextIndex: 14, reference: "In conjunction", fired: false },
					{ time: 115.00, type: "jump", nextIndex: 15, reference: "By a girl that drives a rambler", fired: false },
					{ time: 119.81, type: "jump", nextIndex: 16, reference: "Is overly concerned", fired: false },
					{ time: 126.60, type: "jump", nextIndex: 17, reference: "Planes and trains", fired: false },
					{ time: 135.65, type: "jump", nextIndex: 18, reference: "evoke a common attitude of blue", fired: false },
					{ time: 143.80, type: "jump", nextIndex: 19, reference: "Unless you have a suitcase", fired: false },
					{ time: 151.23, type: "jump", nextIndex: 20, reference: "And the cargo", fired: false },
					{ time: 161.37, type: "jump", nextIndex: 21, reference: "A foreign affair juxtaposed", fired: false },
					{ time: 168.80, type: "jump", nextIndex: 22, reference: "And domestically approved", fired: false },
					{ time: 175.50, type: "jump", nextIndex: 23, reference: "Is mysteriously attractive", fired: false },
					{ time: 184.55, type: "jump", nextIndex: 24, reference: "It will only be parlayed", fired: false },
					{ time: 196.51, type: "jump", nextIndex: 25, reference: "Outro", fired: false },
					{ time: 208.625, type: "Y1pause", nextIndex: 26, reference: "song ended", fired: false }
				]
			},

			"lastWaltz": {
				base: "theLastGreatWaltz",
				display: "The Last Great Waltz",
				bouncesPerLine: 8,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 36,
				font: "Consolas",
				lyricsFile: "theLastGreatWaltz.lyric",
				chords: "lastGreatWaltzChords_v4.jpg",
				credits: `The Last Great Waltz\nWritten by Mason Williams\nJoe Rubinski, Chris Sullivan, Bob Hewus — vocals\nChris Sullivan — guitar\nDave Charron — keyboards\nBob Hewus — bass\nDave Reade — vocals\nISRB\nSt. Clair College, Windsor, Ontario, 1979`,
				appointments: [
					{ time: 0.00, type: "jump", nextIndex: 99, reference: "Beginning", fired: false },
					{ time: 9.45, type: "jump", nextIndex: 1, reference: "Jonathan W. Astor", fired: false },
					{ time: 12.91, type: "jump", nextIndex: 2, reference: "He danced the day", fired: false },
					{ time: 16.37, type: "jump", nextIndex: 3, reference: "The samba and the tango", fired: false },
					{ time: 19.54, type: "jump", nextIndex: 4, reference: "But most he liked to dance", fired: false },
					{ time: 27.27, type: "jump", nextIndex: 5, reference: "I like the waltz - Chorus 1", fired: false },
					{ time: 31.93, type: "jump", nextIndex: 6, reference: "Oh there are some dances", fired: false },
					{ time: 36.56, type: "jump", nextIndex: 7, reference: "I like the waltz simply because", fired: false },
					{ time: 41.10, type: "jump", nextIndex: 8, reference: "It makes me feel so dancy", fired: false },
					{ time: 52.02, type: "jump", nextIndex: 9, reference: "One day he got an invitation", fired: false },
					{ time: 55.48, type: "jump", nextIndex: 10, reference: "And he decided to accept", fired: false },
					{ time: 59.08, type: "jump", nextIndex: 11, reference: "To dance with lovely ladies", fired: false },
					{ time: 62.53, type: "jump", nextIndex: 12, reference: "Or even fat and ugly ones", fired: false },
					{ time: 69.48, type: "jump", nextIndex: 13, reference: "But at the dance the same old story", fired: false },
					{ time: 73.12, type: "jump", nextIndex: 14, reference: "He was a erfectionist so none would dance", fired: false },
					{ time: 76.58, type: "jump", nextIndex: 15, reference: "And so he thought he'd just go home", fired: false },
					{ time: 79.96, type: "jump", nextIndex: 16, reference: "And in the hall he spied a girl", fired: false },
					{ time: 92.40, type: "jump", nextIndex: 17, reference: "I like the waltz, it has its faultz", fired: false },
					{ time: 96.95, type: "jump", nextIndex: 18, reference: "It's not much fun unless danced by two", fired: false },
					{ time: 101.50, type: "jump", nextIndex: 19, reference: "I wish I knew somebody who", fired: false },
					{ time: 106.05, type: "jump", nextIndex: 20, reference: "Would waltz with me, i'm so blue Danube", fired: false },
					{ time: 113.76, type: "jump", nextIndex: 21, reference: "She was standing by herself there in a little nook", fired: false },
					{ time: 117.14, type: "jump", nextIndex: 22, reference: "He quietly crept to where she was to", fired: false },
					{ time: 120.68, type: "jump", nextIndex: 23, reference: "She was a little different", fired: false },
					{ time: 124.38, type: "jump", nextIndex: 24, reference: "For she did not have two good legs", fired: false },
					{ time: 132.42, type: "jump", nextIndex: 25, reference: "I like the waltz - Chorus 4", fired: false },
					{ time: 137.15, type: "jump", nextIndex: 26, reference: "I have three legs", fired: false },
					{ time: 141.88, type: "jump", nextIndex: 27, reference: "I like the waltz mostly because", fired: false },
					{ time: 146.43, type: "jump", nextIndex: 28, reference: "I have to dance all by myself", fired: false },
					{ time: 154.42, type: "jump", nextIndex: 29, reference: "Jonathan W. Astor asked her", fired: false },
					{ time: 158.24, type: "jump", nextIndex: 30, reference: "And she answered Yes sir", fired: false },
					{ time: 161.43, type: "jump", nextIndex: 31, reference: "So they began to dance in a most peculiar way", fired: false },
					{ time: 165.17, type: "jump", nextIndex: 32, reference: "For she had three legs he had two", fired: false },
					{ time: 172.62, type: "jump", nextIndex: 33, reference: "They like the waltz", fired: false },
					{ time: 176.44, type: "jump", nextIndex: 34, reference: "But who's to blame, we can't decide", fired: false },
					{ time: 180.37, type: "jump", nextIndex: 35, reference: "Maybe it's him, maybe it's her", fired: false },
					{ time: 184.18, type: "jump", nextIndex: 36, reference: "But it is them", fired: false },
					{ time: 209.53, type: "Y1pause", nextIndex: 37, reference: "song ended", fired: false }
				]
			},	
			"misterTut": {
				base: "misterTut",
				display: "Mr. Tut",
				bouncesPerLine: 8,
				bounceDuration: 1.05,
				background: "background.jpg",
				fontSize: 36,
				font: "Consolas",
				chords: "mrTutChords_v3.jpg",
				lyricsFile: "misterTut.lyric",
				credits: `Mr. Tut\nWritten by Michael Smith\nChris Sullivan — vocals, guitar\nArts Court, Ottawa, 1987`,
				appointments: [
					{ time: 0.00, type: "jump", nextIndex: 0, reference: "Intro - instrumental", fired: false },
					{ time: 10.77, type: "jump", nextIndex: 1, reference: "Oh Mister Tut what good's it do", fired: false },
					{ time: 15.27, type: "jump", nextIndex: 2, reference: "They love your chair", fired: false },
					{ time: 19.69, type: "jump", nextIndex: 3, reference: "Egyptian nights were never colder", fired: false },
					{ time: 24.15, type: "jump", nextIndex: 4, reference: "And now your friends are thousands of years older", fired: false },
					{ time: 29.31, type: "jump", nextIndex: 5, reference: "Whatever happened to that gang down by the Sphinx", fired: false },
					{ time: 33.45, type: "jump", nextIndex: 6, reference: "Seems they're only forty winks away", fired: false },
					{ time: 37.95, type: "jump", nextIndex: 7, reference: "Those girls from Cairo with their belly button jewels", fired: false },
					{ time: 42.10, type: "jump", nextIndex: 8, reference: "Made you play the fool yesterday", fired: false },
					{ time: 46.44, type: "jump", nextIndex: 9, reference: "And now you keep in shape with Elmer's glue", fired: false },
					{ time: 50.94, type: "jump", nextIndex: 10, reference: "Cause you're all wrapped up", fired: false },
					{ time: 57.73, type: "jump", nextIndex: 11, reference: "Oh Mister Tut they love the mask", fired: false },
					{ time: 62.51, type: "jump", nextIndex: 12, reference: "But do they love you honey sweetheart don't ask", fired: false },
					{ time: 66.84, type: "jump", nextIndex: 13, reference: "Where's those baby browns and that pearly smile", fired: false },
					{ time: 71.10, type: "jump", nextIndex: 14, reference: "That smile that drove em wild by the early Nile", fired: false },
					{ time: 76.19, type: "jump", nextIndex: 15, reference: "You make one terrific hieroglyphic", fired: false },
					{ time: 80.57, type: "jump", nextIndex: 16, reference: "Centuries of standing sideways", fired: false },
					{ time: 85.15, type: "jump", nextIndex: 17, reference: "Those girls from Cairo who filled your heart with lust", fired: false },
					{ time: 89.27, type: "jump", nextIndex: 18, reference: "They've all turned to dust yesterday", fired: false },
					{ time: 93.19, type: "jump", nextIndex: 19, reference: "And those bandages didn't do that much for you", fired: false },
					{ time: 97.76, type: "jump", nextIndex: 20, reference: "Cause you're all wrapped up", fired: false },
					{ time: 104.46, type: "jump", nextIndex: 21, reference: "Oh Mister Tut they dig the tomb", fired: false },
					{ time: 109.43, type: "jump", nextIndex: 22, reference: "All that gold leaf brightens up the room", fired: false },
					{ time: 113.05, type: "jump", nextIndex: 23, reference: "But what's the diff when you're stiff", fired: false },
					{ time: 118.02, type: "jump", nextIndex: 24, reference: "When your ears have spent five thousand years decaying", fired: false },
					{ time: 122.99, type: "jump", nextIndex: 25, reference: "What does it matter what possessions you may boast", fired: false },
					{ time: 127.38, type: "jump", nextIndex: 26, reference: "When you're just a ghost", fired: false },
					{ time: 131.01, type: "jump", nextIndex: 27, reference: "Your sarcophagus is glowing", fired: false },
					{ time: 135.59, type: "jump", nextIndex: 28, reference: "Who cares how rich you are love", fired: false },
					{ time: 140.00, type: "jump", nextIndex: 29, reference: "Call Nautilus they might even refund your dues", fired: false },
					{ time: 144.24, type: "jump", nextIndex: 30, reference: "Cause you're all wrapped up", fired: false },
					{ time: 151.50, type: "jump", nextIndex: 31, reference: "Guitar riff", fired: false },
					{ time: 157.93, type: "jump", nextIndex: 32, reference: "Oh Mister Tut you wait and see", fired: false },
					{ time: 162.52, type: "jump", nextIndex: 33, reference: "Another few thousand years", fired: false },
					{ time: 166.72, type: "jump", nextIndex: 34, reference: "And I'll have all my little treasures", fired: false },
					{ time: 170.73, type: "jump", nextIndex: 35, reference: "A CD of Sergeant Pepper's", fired: false },
					{ time: 175.89, type: "jump", nextIndex: 36, reference: "A little dried out Maui wowee", fired: false },
					{ time: 180.38, type: "jump", nextIndex: 37, reference: "A letter from my honey", fired: false },
					{ time: 184.48, type: "jump", nextIndex: 38, reference: "Some peanut butter sandwiches", fired: false },
					{ time: 189.24, type: "jump", nextIndex: 39, reference: "Not much gold or silver", fired: false },
					{ time: 193.44, type: "jump", nextIndex: 40, reference: "That in my way I'll be just like you", fired: false },
					{ time: 198.23, type: "jump", nextIndex: 41, reference: "All wrapped up in them dead Egyptian blues", fired: false },
					{ time: 202.67, type: "jump", nextIndex: 42, reference: "Coda - All wrapped up", fired: false },
					{ time: 204.91, type: "jump", nextIndex: 43, reference: "Coda - All wrapped up", fired: false },
					{ time: 207.20, type: "jump", nextIndex: 44, reference: "Coda - All wrapped up in them dead Egyptian blues", fired: false },
					{ time: 220.00, type: "Y1pause", nextIndex: 45, reference: "song ended", fired: false }
				]
			},
			"goodman": {
				base: "twentiethCentury",
				display: "The Twentieth Century is Almost Over",
				bouncesPerLine: 8,
				bounceDuration: 0.75,
				background: "background.jpg",
				fontSize: 36,
				font: "Consolas",
				artwork: "twentiethCentury-art.jpg",
				credits: `The Twentieth Century is Almost Over\nWritten by Steve Goodman\nChris Sullivan — banjo\nKathleen Johnson, Joel Leblanc, Sally Thompson — vocals\nArts Court, Ottawa, 1987`,
				lyricsFile: "twentiethCentury.lyric",
				chords: "twentiethCenturyChords_v4.jpg",
				appointments: [
					{ time: 0.00, type: "jump", nextIndex: 0, reference: "Intro", fired: false },
					{ time: 12.11, type: "jump", nextIndex: 1, reference: "Back in Eighteen Ninety Nine", fired: false },
					{ time: 15.48, type: "jump", nextIndex: 2, reference: "When everybody sang Auld Lang Syne", fired: false },
					{ time: 19.14, type: "jump", nextIndex: 3, reference: "A hundred years took a long long time", fired: false },
					{ time: 22.80, type: "jump", nextIndex: 4, reference: "For every boy and girl", fired: false },
					{ time: 27.87, type: "jump", nextIndex: 5, reference: "Now there's only one thing", fired: false },
					{ time: 32.35, type: "jump", nextIndex: 6, reference: "Where did the 20th century go", fired: false },
					{ time: 35.44, type: "jump", nextIndex: 7, reference: "I'd swear it was here just a minute ago", fired: false },
					{ time: 39.10, type: "jump", nextIndex: 8, reference: "All over this world", fired: false },
					{ time: 42.47, type: "jump", nextIndex: 9, reference: "And now the 20th century", fired: false },
					{ time: 46.41, type: "jump", nextIndex: 10, reference: "Almost over almost over", fired: false },
					{ time: 50.47, type: "jump", nextIndex: 11, reference: "The 20th century is almost over - chorus 1", fired: false },
					{ time: 54.00, type: "jump", nextIndex: 12, reference: "All over this world", fired: false },
					{ time: 57.94, type: "jump", nextIndex: 13, reference: "All over this world chorus", fired: false },
					{ time: 61.88, type: "jump", nextIndex: 14, reference: "All over this world chorus", fired: false },
					{ time: 65.26, type: "jump", nextIndex: 15, reference: "The 20th century is almost over repeat", fired: false },
					{ time: 69.16, type: "jump", nextIndex: 16, reference: "All over this world", fired: false },
					{ time: 74.36, type: "jump", nextIndex: 17, reference: "Does anyone remember the Great Depression", fired: false },
					{ time: 78.20, type: "jump", nextIndex: 18, reference: "I read all about it in True Confession", fired: false },
					{ time: 81.84, type: "jump", nextIndex: 19, reference: "I'm sorry I was late", fired: false },
					{ time: 85.75, type: "jump", nextIndex: 20, reference: "But somebody put me on hold", fired: false },
					{ time: 91.12, type: "jump", nextIndex: 21, reference: "Has anybody seen my linoleum floors", fired: false },
					{ time: 94.97, type: "jump", nextIndex: 22, reference: "Petroleum jelly and two World Wars", fired: false },
					{ time: 98.77, type: "jump", nextIndex: 23, reference: "They got stuck in the revolving doors", fired: false },
					{ time: 102.51, type: "jump", nextIndex: 24, reference: "All over this world", fired: false },
					{ time: 105.81, type: "jump", nextIndex: 25, reference: "And now the 20th century is almost over", fired: false },
					{ time: 110.00, type: "jump", nextIndex: 26, reference: "Almost over almost over", fired: false },
					{ time: 113.68, type: "jump", nextIndex: 27, reference: "The 20th century is almost over", fired: false },
					{ time: 117.44, type: "jump", nextIndex: 28, reference: "All over this world", fired: false },
					{ time: 121.47, type: "jump", nextIndex: 29, reference: "All over this world", fired: false },
					{ time: 125.11, type: "jump", nextIndex: 30, reference: "All over this world", fired: false },
					{ time: 128.48, type: "jump", nextIndex: 31, reference: "The 20th century is almost over", fired: false },
					{ time: 132.52, type: "jump", nextIndex: 32, reference: "All over this world", fired: false },
					{ time: 138.11, type: "jump", nextIndex: 33, reference: "Winter's getting colder, summre's gettiin' hotter", fired: false },
					{ time: 141.61, type: "jump", nextIndex: 34, reference: "Wishin well's wishin for another drop of water", fired: false },
					{ time: 145.53, type: "jump", nextIndex: 35, reference: "Mother Earth is blushin cause somebody caught 'er", fired: false },
					{ time: 148.89, type: "jump", nextIndex: 36, reference: "Makin love to the Man in the Moon", fired: false },
					{ time: 154.46, type: "jump", nextIndex: 37, reference: "Tell me how you gonna keep em down", fired: false },
					{ time: 158.60, type: "jump", nextIndex: 38, reference: "Now that outer space has lost its charm", fired: false },
					{ time: 162.29, type: "jump", nextIndex: 39, reference: "Somebody set off the burglar alarm", fired: false },
					{ time: 165.87, type: "jump", nextIndex: 40, reference: "And not a minute too soon", fired: false },
					{ time: 169.30, type: "jump", nextIndex: 41, reference: "Because the 20th century is almost over",fired: false },
					{ time: 173.46, type: "jump", nextIndex: 42, reference: "Almost over almost over", fired: false },
					{ time: 176.81, type: "jump", nextIndex: 43, reference: "The 20th century is almost over", fired: false },
					{ time: 180.83, type: "jump", nextIndex: 44, reference: "All over this world", fired: false },
					{ time: 184.63, type: "jump", nextIndex: 45, reference: "All over this world", fired: false },
					{ time: 188.82, type: "jump", nextIndex: 46, reference: "All over this world", fired: false },
					{ time: 192.05, type: "jump", nextIndex: 47, reference: "The 20th century is almost over", fired: false },
					{ time: 195.83, type: "jump", nextIndex: 48, reference: "All over this world", fired: false },
					{ time: 203.41, type: "jump", nextIndex: 49, reference: "Old Father Time's got his toes a tappin", fired: false },
					{ time: 207.19, type: "jump", nextIndex: 50, reference: "Standing in the window, grumblin' and a-rappin", fired: false },
					{ time: 210.95, type: "jump", nextIndex: 51, reference: "Everybody's waiting for something to happen", fired: false },
					{ time: 214.65, type: "jump", nextIndex: 52, reference: "Tell me if it happens to you", fired: false },
					{ time: 220.26, type: "jump", nextIndex: 53, reference: "The Judgment Day is getting nearer", fired: false },
					{ time: 223.97, type: "jump", nextIndex: 54, reference: "There it is in the rear view mirror", fired: false },
					{ time: 227.76, type: "jump", nextIndex: 55, reference: "If you duck down I could see a little clearer", fired: false },
					{ time: 231.54, type: "jump", nextIndex: 56, reference: "All over this world", fired: false },
					{ time: 235.00, type: "jump", nextIndex: 57, reference: "And now the 20th century is almost over", fired: false },
					{ time: 239.29, type: "jump", nextIndex: 58, reference: "Almost over almost over - chorus 4", fired: false },
					{ time: 242.90, type: "jump", nextIndex: 59, reference: "The 20th century is almost over", fired: false },
					{ time: 246.68, type: "jump", nextIndex: 60, reference: "All over this world", fired: false },
					{ time: 250.57, type: "jump", nextIndex: 61, reference: "All over this world", fired: false },
					{ time: 254.35, type: "jump", nextIndex: 62, reference: "All over this world", fired: false },
					{ time: 258.00, type: "jump", nextIndex: 63, reference: "The 20th century is almost over", fired: false },
					{ time: 261.58, type: "jump", nextIndex: 64, reference: "All over this world", fired: false },
					{ time: 265.96, type: "jump", nextIndex: 65, reference: "One more time: the 20th century is almost over", fired: false },
					{ time: 270.88, type: "jump", nextIndex: 66, reference: "Almost over almost over", fired: false },
					{ time: 274.66, type: "jump", nextIndex: 67, reference: "The 20th century is almost over", fired: false },
					{ time: 278.76, type: "jump", nextIndex: 68, reference: "All over this world", fired: false },
					{ time: 282.38, type: "jump", nextIndex: 69, reference: "All over this world", fired: false },
					{ time: 286.44, type: "jump", nextIndex: 70, reference: "All over this world", fired: false },
					{ time: 289.96, type: "jump", nextIndex: 71, reference: "The 20th century is almost over", fired: false },
					{ time: 294.15, type: "jump", nextIndex: 72, reference: "All over this world", fired: false },
					{ time: 332.18, type: "Y1pause", nextIndex: 73, reference: "song ended", fired: false }
				]
			},
		    "dylan": {
				base: "accuratedontThinkTwice",
				display: "Don't Think Twice, It's All Right",
				bouncesPerLine: 8,
				bounceDuration: 1.06,
				background: "background.jpg",
				fontSize: 36,
				font: "Consolas",
                chords: "dontThinkTwiceChords_v4.jpg",
				lyricsFile: "accuratedontThinkTwice.lyric",
				credits: `Don't Think Twice, It's All Right\nWritten and performed by Bob Dylan\nvocals, guitar, harmonica\nProduced by John Hammond\nColumbia Records, 1963\nFrom: The Freewheelin' Bob Dylan`,				appointments: [
					{ time: 0.00, type: "jump", nextIndex: 0,  reference: "intro", fired: false },
					{ time: 7.12, type: "jump", nextIndex: 1,  reference: "Well it ain't no use to sit and wonder why, baby", fired: false },
					{ time: 12.37, type: "jump", nextIndex: 2,  reference: "If'n you don't know by now", fired: false },
					{ time: 16.12, type: "jump", nextIndex: 3,  reference: "An ain't no use to sit and wonder why baby", fired: false },
					{ time: 21.18, type: "jump", nextIndex: 4,  reference: "It'll never do somehow", fired: false },
					{ time: 24.37, type: "jump", nextIndex: 5,  reference: "When your rooster crows", fired: false },
					{ time: 30.00, type: "jump", nextIndex: 6,  reference: "Look out your window", fired: false },
					{ time: 34.12, type: "jump", nextIndex: 7,  reference: "You're the reason I'm a travelin on", fired: false },
					{ time: 38.24, type: "jump", nextIndex: 8,  reference: "Don't think twice chorus 1", fired: false },
					{ time: 42.74, type: "jump", nextIndex: 9,  reference: "Harmonica break 1", fired: false },
					{ time: 53.61, type: "jump", nextIndex: 10,  reference: "It ain't no use in turnin on your light babe", fired: false },
					{ time: 58.11, type: "jump", nextIndex: 11, reference: "The light I never knowed", fired: false },
					{ time: 62.52, type: "jump", nextIndex: 12, reference: "An it ain't no use in turnin on your light babe repeat", fired: false },
					{ time: 67.52, type: "jump", nextIndex: 13, reference: "I'm on the dark side of the road", fired: false },
					{ time: 70.92, type: "jump", nextIndex: 14, reference: "I wish there was somethin you would do or say", fired: false },
					{ time: 75.64, type: "jump", nextIndex: 15, reference: "To try and make me change my mind and stay", fired: false },
					{ time: 80.00, type: "jump", nextIndex: 16, reference: "We never did too much talkin anyway", fired: false },
					{ time: 84.16, type: "jump", nextIndex: 17, reference: "So don't think twice chorus 2", fired: false },
					{ time: 87.47, type: "jump", nextIndex: 18, reference: "Harmonica break", fired: false },
					{ time: 97.27, type: "jump", nextIndex: 19, reference: "No it ain't no use in callin out my name gal", fired: false },
					{ time: 102.44, type: "jump", nextIndex: 20, reference: "Like you never done before", fired: false },
					{ time: 105.96, type: "jump", nextIndex: 21, reference: "An it ain't no use in callin out my name gal repeat", fired: false },
					{ time: 110.95, type: "jump", nextIndex: 22, reference: "I can't hear you anymore", fired: false },
					{ time: 114.46, type: "jump", nextIndex: 23, reference: "I'm a thinkin and a wondrin walkin down the road", fired: false },
					{ time: 118.89, type: "jump", nextIndex: 24, reference: "I once loved a woman a child I'm told", fired: false },
					{ time: 123.32, type: "jump", nextIndex: 25, reference: "I give her my heart but she wanted my soul", fired: false },
					{ time: 127.95, type: "jump", nextIndex: 26, reference: "Don't think twice chorus 3", fired: false },
					{ time: 130.73, type: "jump", nextIndex: 27, reference: "Harmonica break", fired: false },
					{ time: 144.40, type: "jump", nextIndex: 28, reference: "So long honey babe", fired: false },
					{ time: 148.28, type: "jump", nextIndex: 29, reference: "Where I'm bound I can't tell", fired: false },
					{ time: 153.27, type: "jump", nextIndex: 30, reference: "Goodbye is too good a word gal", fired: false },
					{ time: 157.89, type: "jump", nextIndex: 31, reference: "So I'll just say fare thee well", fired: false },
					{ time: 161.77, type: "jump", nextIndex: 32, reference: "I ain't sayin you treated me unkind", fired: false },
					{ time: 165.83, type: "jump", nextIndex: 33, reference: "You could have done better but I don't mind", fired: false },
					{ time: 170.55, type: "jump", nextIndex: 34, reference: "You just kinda wasted my precious time", fired: false },
					{ time: 174.58, type: "jump", nextIndex: 35, reference: "But don't think twice", fired: false },
					{ time: 177.85, type: "jump", nextIndex: 36, reference: "Harmonica break", fired: false },
					{ time: 186.52, type: "jump", nextIndex: 37, reference: "Harmonica break", fired: false },
					{ time: 194.58, type: "jump", nextIndex: 38, reference: "Harmonica break", fired: false },
					{ time: 199.63, type: "jump", nextIndex: 39, reference: "Harmonica break", fired: false },
					{ time: 203.58, type: "jump", nextIndex: 40, reference: "Harmonica break", fired: false },
					{ time: 208.08, type: "jump", nextIndex: 41, reference: "Harmonica break", fired: false },
					{ time: 213.93, type: "Y1pause", nextIndex: 42, reference: "End", fired: false }
				]
			  },
		  "Rogers": {
			base: "maryEllenCarterJoelChris",
			display: "Mary Ellen Carter",
			bouncesPerLine: 8,
			bounceDuration: 1.2,
			background: "background.jpg",
			fontSize: 32,
			font: "Consolas",
			lyricsFile: "maryEllenCarterJoelChris.lyric",
			chords: "maryEllenCarterChords_v4 .jpg",
			credits: `The Mary Ellen Carter\nWritten by Stan Rogers\nChris Sullivan — vocals, 12-string guitar\nJoel Leblanc — vocals, 6-string guitar\nArts Court, Ottawa, 1987\nI played this song in DADGAD with the capo on the 5th fret.\nThat is as near as I can tell how Stan used to play it.\nThat puts it in the key of G.\nThe ukulele chords under the Promptoid K key are in G.`,			appointments: [
			{ time: 0.00, type: "jump", nextIndex: 0,  reference: "Intro", fired: false },
			{ time: 5.88, type: "jump", nextIndex: 1,  reference: "Intro", fired: false },
			{ time: 11.75, type: "jump", nextIndex: 2,  reference: "Intro", fired: false },
			{ time: 17.63, type: "jump", nextIndex: 3,  reference: "Intro", fired: false },
			{ time: 23.85, type: "jump", nextIndex: 4,  reference: "She went down last October", fired: false },
			{ time: 28.54, type: "jump", nextIndex: 5,  reference: "The skipper he'd been drinking", fired: false },
			{ time: 33.36, type: "jump", nextIndex: 6,  reference: "Too close to Three Mile Rock", fired: false },
			{ time: 38.04, type: "jump", nextIndex: 7,  reference: "And the Mary Ellen Carter settled low", fired: false },
			{ time: 43.09, type: "jump", nextIndex: 8,  reference: "There was just us five aboard her when she finally was awash", fired: false },
			{ time: 48.13, type: "jump", nextIndex: 9,  reference: "We worked like hell to save her, all heedless of the cost", fired: false },
			{ time: 52.95, type: "jump", nextIndex: 10,  reference: "And the groan she gave as ahe went down it caused us to proclaim", fired: false },
			{ time: 57.69, type: "jump", nextIndex: 11,  reference: "That the Mary Ellen Carter would rise again", fired: false },
			{ time: 61.02, type: "jump", nextIndex: 12,  reference: "guitar break", fired: false },
			{ time: 78.82, type: "jump", nextIndex: 13,  reference: "Well the owners wrote her off, not a nickel would they spend", fired: false },
			{ time: 83.67, type: "jump", nextIndex: 14,  reference: "She gave twenty years of service", fired: false },
			{ time: 88.60, type: "jump", nextIndex: 15, reference: "But insurance paid the loss to us", fired: false },
			{ time: 93.46, type: "jump", nextIndex: 16, reference: "Then they laughed at us and said we had to go", fired: false },
			{ time: 98.50, type: "jump", nextIndex: 17, reference: "But we talked of her all winter", fired: false },
			{ time: 103.53, type: "jump", nextIndex: 18, reference: "She's worth a quarter million", fired: false },
			{ time: 108.29, type: "jump", nextIndex: 19, reference: "And with every jar that hit the bar", fired: false },
			{ time: 113.05, type: "jump", nextIndex: 20, reference: "And make the Mary Ellen Carter rise again - v2", fired: false },
			{ time: 118.37, type: "jump", nextIndex: 21, reference: "Rise again rise again - chorus 1", fired: false },
			{ time: 123.40, type: "jump", nextIndex: 22, reference: "Let her name not be lost - chorus 1", fired: false },
			{ time: 128.69, type: "jump", nextIndex: 23, reference: "Those who loved her best - chorus 1", fired: false },
			{ time: 133.19, type: "jump", nextIndex: 24, reference: "Will make the Mary Ellen Carter rise again - chorus 1", fired: false },
			{ time: 137.67, type: "jump", nextIndex: 25, reference: "guitar", fired: false },
			{ time: 146.35, type: "jump", nextIndex: 26, reference: "All spring now we've been with her", fired: false },
			{ time: 151.40, type: "jump", nextIndex: 27, reference: "Three dives a day in hard hat suit", fired: false },
			{ time: 156.42, type: "jump", nextIndex: 28, reference: "Thank God it's only sixty feet", fired: false },
			{ time: 161.40, type: "jump", nextIndex: 29, reference: "Or I'd never have the strength to go below", fired: false },
			{ time: 166.33, type: "jump", nextIndex: 30, reference: "But we've patched her rents stopped her vents", fired: false },
			{ time: 171.37, type: "jump", nextIndex: 31, reference: "Put cables to her fore and aft", fired: false },
			{ time: 176.29, type: "jump", nextIndex: 32, reference: "Tomorrow noon we hit the air", fired: false },
			{ time: 181.40, type: "jump", nextIndex: 33, reference: "And make the Mary Ellen Carter rise again - v3", fired: false },
			{ time: 186.65, type: "jump", nextIndex: 34, reference: "Rise again rise again - chorus 2", fired: false },
			{ time: 191.96, type: "jump", nextIndex: 35, reference: "Let her name not be lost - chorus 2", fired: false },
			{ time: 197.14, type: "jump", nextIndex: 36, reference: "Those who loved her best - chorus 2", fired: false },
			{ time: 206.51, type: "jump", nextIndex: 37, reference: "Will make the Mary Ellen Carter rise again - chorus 2", fired: false },
			{ time: 209.44, type: "jump", nextIndex: 38, reference: "For we couldn't leave her there", fired: false },
			{ time: 214.62, type: "jump", nextIndex: 39, reference: "She'd saved our lives so many times", fired: false },
			{ time: 219.44, type: "jump", nextIndex: 40, reference: "And the laughing drunken rats", fired: false },
			{ time: 224.98, type: "jump", nextIndex: 41, reference: "They won't be laughing in another day", fired: false },
			{ time: 230.00, type: "jump", nextIndex: 42, reference: "And you to whom adversity has dealt the final blow", fired: false },
			{ time: 234.77, type: "jump", nextIndex: 43, reference: "With smiling bastards lying to you", fired: false },
			{ time: 240.00, type: "jump", nextIndex: 44, reference: "Turn to and put out all your strength", fired: false },
			{ time: 244.69, type: "jump", nextIndex: 45, reference: "And like the Mary Ellen Carter rise again - v4", fired: false },
			{ time: 249.93, type: "jump", nextIndex: 46, reference: "Rise again rise again", fired: false },
			{ time: 255.18, type: "jump", nextIndex: 47, reference: "Though your heart it be broken and lfe about to end", fired: false },
			{ time: 260.54, type: "jump", nextIndex: 48, reference: "No matter what you've lost be it a home a love a friend,", fired: false },
			{ time: 265.35, type: "jump", nextIndex: 49, reference: "like the Mary Ellen Carter rise again", fired: false },
			{ time: 270.35, type: "jump", nextIndex: 50, reference: "Rise again rise again", fired: false },
			{ time: 275.81, type: "jump", nextIndex: 51, reference: "Though your heart it be broken and lfe about to end", fired: false },
			{ time: 281.02, type: "jump", nextIndex: 52, reference: "No matter what you've lost be it a home a love a friend", fired: false },
			{ time: 286.15, type: "jump", nextIndex: 53, reference: "like the Mary Ellen Carter rise again", fired: false },
			{ time: 322.45, type: "Y1pause", nextIndex: 54, reference: "song ended", fired: false}
			]
		  },
		  "Four Strong Winds": {
			base: "fourStrongWinds",
			display: "Four Strong Winds",
			bouncesPerLine: 8,
			bounceDuration: 1.10,
			background: "background.jpg",
			fontSize: 36,
			font: "Consolas",
			chords: "fourStrongWindsChords_v3.jpg",
			lyricsFile: "fourStrongWinds.lyric",
			credits: `Four Strong Winds\nWritten by Ian Tyson\nNeil Young — vocals, guitar\nEmmylou Harris — vocals\nPegi Young — harmony vocals\nBen Keith — steel guitar\nSpooner Oldham — keyboards\nGrant Boatwright — harmony vocals, guitar\nDir. Jonathan Demme\nRyman Auditorium, Nashville, 2005`,			
			appointments: [
			{ time: 0.00, type: "jump", nextIndex: 0,  reference: "Intro", fired: false },
			{ time: 16.72, type: "jump", nextIndex: 1,  reference: "Think I'll go out to Alberta", fired: false},   
			{ time: 21.01, type: "jump", nextIndex: 2,  reference: "Weather's good there in the fall", fired: false },
			{ time: 24.68, type: "jump", nextIndex: 3,  reference: "I got some friends that I can go to working for", fired: false },
			{ time: 33.65, type: "jump", nextIndex: 4,  reference: "Still I wish you'd change your mind", fired: false },
			{ time: 38.14, type: "jump", nextIndex: 5,  reference: "If I asked you one more time", fired: false },
			{ time: 42.54, type: "jump", nextIndex: 6,  reference: "But we've been through that a hundred times or more", fired: false },
			{ time: 50.61, type: "jump", nextIndex: 7,  reference: "Four strong winds that blow lonely", fired: false },
			{ time: 55.27, type: "jump", nextIndex: 8,  reference: "Seven seas that run high", fired: false },
			{ time: 59.18, type: "jump", nextIndex: 9,  reference: "All those things that don't change come what may", fired: false },
			{ time: 68.12, type: "jump", nextIndex: 10, reference: "If the good times are all gone", fired: false },
			{ time: 72.81, type: "jump", nextIndex: 11, reference: "And I'm bound for moving on", fired: false },
			{ time: 76.68, type: "jump", nextIndex: 12, reference: "I'll look for you if I'm ever back tis way", fired: false },
			{ time: 85.68, type: "jump", nextIndex: 13, reference: "If I  get there before the snow flies", fired: false },
			{ time: 90.16, type: "jump", nextIndex: 14, reference: "And if things are looking good", fired: false },
			{ time: 94.33, type: "jump", nextIndex: 15, reference: "You could meet me if I send you down the fare", fired: false },
			{ time: 102.18, type: "jump", nextIndex: 16, reference: "But by then it would be wimter", fired: false },
			{ time: 107.07, type: "jump", nextIndex: 17, reference: "Not too much for you to do", fired: false },
			{ time: 111.35, type: "jump", nextIndex: 18, reference: "And those winds sure can blow cold way out there", fired: false },
			{ time: 119.81, type: "jump", nextIndex: 19, reference: "Four strong winds that blow lonely", fired: false },
			{ time: 124.20, type: "jump", nextIndex: 20, reference: "Seven seas that run high", fired: false },
			{ time: 128.49, type: "jump", nextIndex: 21, reference: "All those things that don't change come what may", fired: false },
			{ time: 137.25, type: "jump", nextIndex: 22, reference: "If the good times are all gone", fired: false },
			{ time: 141.54, type: "jump", nextIndex: 23, reference: "And I'm bound for moving on", fired: false },
			{ time: 145.62, type: "jump", nextIndex: 24, reference: "I'll look for you if I'm ever back this way", fired: false },
			{ time: 154.39, type: "jump", nextIndex: 25, reference: "pedal steel solo", fired: false },
			{ time: 171.22, type: "jump", nextIndex: 26, reference: "Still I wish you'd change your mind", fired: false },
			{ time: 176.00, type: "jump", nextIndex: 27,  reference: "If I asked you one more time", fired: false },
			{ time: 180.20, type: "jump", nextIndex: 28,  reference: "But we've been through that a hundred times or more", fired: false },
			{ time: 188.57, type: "jump", nextIndex: 29, reference: "Four strong winds that blow lonely", fired: false },
			{ time: 193.14, type: "jump", nextIndex: 30, reference: "Seven seas that run high", fired: false },
			{ time: 197.62, type: "jump", nextIndex: 31, reference: "All those things that don't change come what may", fired: false },
			{ time: 206.40, type: "jump", nextIndex: 32, reference: "If the good times are all gone", fired:  false },
			{ time: 210.88, type: "jump", nextIndex: 33, reference: "And I'm bound for moving on", fired: false },
			{ time: 214.96, type: "jump", nextIndex: 34, reference: "I'll look for you if I'm ever back this way", fired: false },
			{ time: 223.52, type: "jump", nextIndex: 35, reference: "I'll look for you if I'm ever back this way", fired: false },
			{ time: 234.30, type: "Y1pause", nextIndex: 36, reference: "song ended", fired: false }
			]
		  },
		  "rainbow": {
			base: "rainbowConnection",
			display: "Rainbow Connection",
			bouncesPerLine: 8,
			bounceDuration: 1.5625,
			background: "background.jpg",
			fontSize: 36,
			font: "Consolas",
			chords: "rainbowConnectionChords_v8.jpg",
			lyricsFile: "rainbowConnection.lyric",
			credits: `Rainbow Connection\nWritten by Paul Williams and Kenneth Ascher\nPerformed by Jim Henson as Kermit the Frog\nProduced by Paul Williams\nA&M Studios, Hollywood, 1978\nAtlantic Records, 1979\nFrom: The Muppet Movie`,
			appointments: [
				{ time: 0.00, type: "jump", nextIndex: 0,  reference: "Intro", fired: false },
				{ time: 6.06, type: "jump", nextIndex: 1,  reference: "Why are there so many songs abour rainbows", fired: false },
				{ time: 12.28, type: "jump", nextIndex: 2,  reference: "And what's on the other side?", fired: false },
				{ time: 18.82, type: "jump", nextIndex: 3,  reference: "Rainbows are visions, but only illusions", fired: false },
				{ time: 24.56, type: "jump", nextIndex: 4,  reference: "And rainbows have nothing to hide", fired: false },
				{ time: 30.94, type: "jump", nextIndex: 5,  reference: "So we've been told", fired: false },
				{ time: 37.17, type: "jump", nextIndex: 6,  reference: "I know they're wrong", fired: false },
				{ time: 43.71, type: "jump", nextIndex: 7,  reference: "Some day we'll find it - chorus 1", fired: false },
				{ time: 49.84, type: "jump", nextIndex: 8,  reference: "The lovers the dreamers - chorus 1", fired: false },
				{ time: 53.94, type: "jump", nextIndex: 9, reference: "break", fired: false },
				{ time: 59.18, type: "jump", nextIndex: 10, reference: "Who said that every wish would be heard and answered", fired: false },
				{ time: 65.25, type: "jump", nextIndex: 11, reference: "When wished on the morning star", fired: false },
				{ time: 71.70, type: "jump", nextIndex: 12, reference: "Somebody thought of that", fired: false },				
				{ time: 77.52, type: "jump", nextIndex: 13, reference: "And look what it's done so far", fired: false },
				{ time: 84.54, type: "jump", nextIndex: 14, reference: "What's so amazing", fired: false },
				{ time: 90.31, type: "jump", nextIndex: 15, reference: "And what do we think we might see", fired: false },
				{ time: 96.99, type: "jump", nextIndex: 16, reference: "Some day we'll find it - chorus 2", fired: false },
				{ time: 102.73, type: "jump", nextIndex: 17, reference: "The lovers the dreamers - chorus 2", fired: false },
				{ time: 107.68, type: "jump", nextIndex: 18, reference: "All of us under its spell", fired: false },
				{ time: 111.98, type: "jump", nextIndex: 19, reference: "We know that it's probably magic", fired: false },
				{ time: 120.48, type: "jump", nextIndex: 20, reference: "Have you been half asleep", fired: false },
				{ time: 126.98, type: "jump", nextIndex: 21, reference: "I've heard them calling my name", fired: false },
				{ time: 132.72, type: "jump", nextIndex: 22, reference: "Is this the sweet sound", fired: false },
				{ time: 138.88, type: "jump", nextIndex: 23, reference: "The voice might be one and the same", fired: false },
				{ time: 145.48, type: "jump", nextIndex: 24, reference: "I've heard it too many times", fired: false },
				{ time: 151.39, type: "jump", nextIndex: 25, reference: "It's something that I'm supposed to be", fired: false },
				{ time: 157.84, type: "jump", nextIndex: 26, reference: "Someday we'll find it - chorus 3", fired: false },
				{ time: 163.83, type: "jump", nextIndex: 27, reference: "The lovers the dreamers - chorus 3", fired: false },
				{ time: 168.88, type: "jump", nextIndex: 28, reference: "Da dee da dee dum", fired: false },
				{ time: 173.24, type: "jump", nextIndex: 29, reference: "Dum dee dee", fired: false },
				{ time: 183.55, type: "Y1pause", nextIndex: 30, reference: "song ended", fired: false }
			]
		  },
    	  "the-visitor": {
			base: "the-visitor",
			display: "The Visitor",
			bouncesPerLine: 4,
			bounceDuration: 0.84375,
			background: "background.jpg",
			fontSize: 36,
			font: "Consolas",
			chords: "theVisitorChords_v4.jpg",
			lyricsFile: "the-visitor.lyric",
			credits: `The Visitor\nWritten by Chris Sullivan\nKathleen Johnson — vocals\nChris Sullivan — guitar\nGreg Jeeves — keyboards, bass, sound effects, engineering\nRecorded 1988`,
			appointments: [
				{ time: 15.42,  type: "jump",     nextIndex: 5,  reference: "5 lines, jump 1 to Verse 1 after intro and Cricket Music 1", fired: false },
				{ time: 42.86,  type: "jump",     nextIndex: 13, reference: "first line of cricket music 3", fired: false },
				{ time: 52.08,  type: "jump",     nextIndex: 16, reference: "11 lines, jump 2 to Verse 2 after Cricket Music 2", fired: false },
				{ time: 88.74,  type: "jump",     nextIndex: 27, reference: "11 lines, jump 3 to Verse 3 after Cricket Music 3", fired: false },
				{ time: 104.15, type: "jump",     nextIndex: 31, reference: "4 lines, jump 4 to Bridge 1", fired: false },
				{ time: 140.56, type: "jump",     nextIndex: 42, reference: "11 lines, jump 5 to Verse 4", fired: false },
				{ time: 156.23, type: "jump",     nextIndex: 46, reference: "4 lines, jump 6 to Bridge 2", fired: false },
				{ time: 216.10, type: "Y1pause",  nextIndex: 61, reference: "song ended", fired: false }
			]
		  },
			"callingUsAway": {
				base: "callingUsAway",
				display: "Calling Us Away",
				bouncesPerLine: 8,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 34,
				font: "Consolas",
				lyricsFile: "callingUsAway.lyric",
				chords: "callingUsAwayChords_v1.jpg",
				credits: `Calling Us Away\nWords and music by Chris Sullivan and Kathleen Johnson\nextra verse by John Newton (hymn "Amazing Grace")\nperformed by Kathleen Johnson\nrecorded and keyboards by Greg Jeeves`,
				appointments: 
				[
					{ time: 0.00, type: "jump", nextIndex: 0, reference: "Intro", fired: false },
					{ time: 20.44, type: "jump", nextIndex: 1,  reference: "I think about my younger days", fired: false },
					{ time: 25.55, type: "jump", nextIndex: 2,  reference: "And the people that I lived with", fired: false },
					{ time: 31.08, type: "jump", nextIndex: 3,  reference: "There were sounds of magic", fired: false },
					{ time: 35.81, type: "jump", nextIndex: 4,  reference: "And echoes from the canyons", fired: false },
					{ time: 41.31, type: "jump", nextIndex: 5,  reference: "We took all we needed", fired: false },
					{ time: 46.51, type: "jump", nextIndex: 6,  reference: "A meal, a drink, and pleasant company", fired: false },
					{ time: 51.31, type: "jump", nextIndex: 7,  reference: "Someone dancing, someone singing", fired: false },
					{ time: 56.55, type: "jump", nextIndex: 8,  reference: "In a house between the mountains", fired: false },
					{ time: 61.79, type: "jump", nextIndex: 9,  reference: "And we danced the dance of life - chorus 1", fired: false },
					{ time: 66.81, type: "jump", nextIndex: 10,  reference: "Like the leaves dance - chorus 1", fired: false },
					{ time: 72.71, type: "jump", nextIndex: 11, reference: "Dancing to the music - chorus 1a", fired: false },
					{ time: 83.19, type: "jump", nextIndex: 12, reference: "Dancing to the music - chorus 1b", fired: false },
					{ time: 104.15, type: "jump", nextIndex: 13, reference: "If you could look through the walls", fired: false },
					{ time: 108.69, type: "jump", nextIndex: 14, reference: "Past the dangers and the changes", fired: false },
					{ time: 114.41, type: "jump", nextIndex: 15, reference: "Down below the waves of feelings", fired: false },
					{ time: 119.13, type: "jump", nextIndex: 16, reference: "And over mountains of the deeds", fired: false },
					{ time: 124.45, type: "jump", nextIndex: 17, reference: "If you could break the chains of habit", fired: false },
					{ time: 130.00, type: "jump", nextIndex: 18, reference: "Unlock my heart and throw away the key", fired: false },
					{ time: 135.15, type: "jump", nextIndex: 19, reference: "And take me over roads", fired: false },
					{ time: 140.00, type: "jump", nextIndex: 20, reference: "To that house between the mountains", fired: false },
					{ time: 145.41, type: "jump", nextIndex: 21, reference: "Where we danced - chorus 2", fired: false },
					{ time: 150.44, type: "jump", nextIndex: 22, reference: "Like the leaves dance - chorus 2", fired: false },
					{ time: 156.33, type: "jump", nextIndex: 23, reference: "Dancing to the music - chorus 2a", fired: false },
					{ time: 166.59, type: "jump", nextIndex: 24, reference: "Dancing to the music - chorus 2b", fired: false },
					{ time: 176.85, type: "jump", nextIndex: 25, reference: "Dancing to the music - chorus 3a", fired: false },
					{ time: 187.33, type: "jump", nextIndex: 26, reference: "Dancing to the music - chorus 3b", fired: false },
					{ time: 201.53, type: "jump", nextIndex: 27, reference: "Calling us away (tag a)", fired: false },
					{ time: 211.79, type: "jump", nextIndex: 28, reference: "Calling us away (tag b)", fired: false },
					{ time: 246.72, type: "Y1pause", nextIndex: 29, reference: "song ends", fired: false },
				]
			},
			
			"yourNameHere": {
				base: "yourNameHere",
				display: "Your Name Here",
				bouncesPerLine: 8,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 34,
				font: "Consolas",
				lyricsFile: "yourNameHere.lyric",
				chords: "yourNameHereChords_v1.jpg",
				credits: `Your Name Here\nWords and music by Chris Sullivan\nChris Sullivan — vocals, guitar\nDave Reade — vocals\nRecording and keyboards - Greg Jeeves`,
				appointments: [
					{ time:  0.00, type: "jump",    nextIndex:  0, reference: "Intro", fired: false },
					{ time:  15.30, type: "jump",    nextIndex:  1, reference: "You're precious", fired: false },
					{ time:  22.54, type: "jump",    nextIndex:  2, reference: "You're a puzzle", fired: false },
					{ time:  30.00, type: "jump",    nextIndex:  3, reference: "Can I reach you", fired: false },
					{ time:  37.17, type: "jump",    nextIndex:  4, reference: "Can I tell you", fired: false },
					{ time:  43.75, type: "jump",    nextIndex:  5, reference: "Substitutions (Bridge 1a)", fired: false },
					{ time:  50.99, type: "jump",    nextIndex:  6, reference: "And your early confirmation (1b)", fired: false },
					{ time:  58.39, type: "jump",    nextIndex:  7, reference: "We ship anywhere (1c)", fired: false },
					{ time:  65.47, type: "jump",    nextIndex:  8, reference: "Please include the total (1d)",fired: false },
					{ time:  73.69, type: "jump",    nextIndex:  9, reference: "The information", fired: false },
					{ time:  81.15, type: "jump",    nextIndex: 10, reference: "Say the word", fired: false },
					{ time:  88.66, type: "jump",    nextIndex: 11, reference: "I respectfully submit", fired: false },
					{ time:  95.73, type: "jump",    nextIndex: 12, reference: "My love is guaranteed", fired: false },
					{ time:  102.15, type: "jump",    nextIndex: 13, reference: "Substitutions (Bridge 2a)", fired: false },
					{ time:  109.51, type: "jump",    nextIndex: 14, reference: "And your early confirmation (2b)", fired: false },
					{ time:  116.95, type: "jump",    nextIndex: 15, reference: "We ship anywhere (2c)", fired: false },
					{ time:  124.19, type: "jump",    nextIndex: 16, reference: "Please include the total (2d)",fired: false },
					{ time:  147.55, type: "jump",    nextIndex: 17, reference: "If I press hard enough (Finale 1)", fired: false },
					{ time:  154.95, type: "jump",    nextIndex: 18, reference: "In any form (Finale 2)", fired: false },
					{ time:  162.35, type: "jump",    nextIndex: 19, reference: "If I press hard enough (Finale 3)", fired: false },
					{ time:  169.51, type: "jump",    nextIndex: 20, reference: "In any form (Finale 4)", fired: false },
					{ time:  184.39, type: "Y1pause", nextIndex: 21, reference: "song ends", fired: false }
				]
			},
			"livingInThePast": {
				base: "livingInThePast",
				display: "Living In The Past",
				bouncesPerLine: 8,
				bounceDuration: 0.7,
				background: "background.jpg",
				fontSize: 34,
				font: "Consolas",
				lyricsFile: "livingInThePast.lyric",
				chords: "livingInThePastChords_v1.jpg",
				credits: `Living In The Past\nWords and music by Chris Sullivan\nChris Sullivan — vocals, guitar`,
				appointments: [
					{ time:   0.01, type: "jump",    nextIndex:  0, reference: "Intro", fired: false },
					{ time:   18.29, type: "jump",    nextIndex:  1, reference: "This year is a lullaby", fired: false },
					{ time:   23.76, type: "jump",    nextIndex:  2, reference: "This year is a field of hay", fired: false },
					{ time:   29.57, type: "jump",    nextIndex:  3, reference: "This year is a wishing star", fired: false },
					{ time:   35.81, type: "jump",    nextIndex:  4, reference: "Wake up don't waste your time", fired: false },
					{ time:   41.70, type: "jump",    nextIndex:  5, reference: "You're younger than your years (V1)", fired: false },
					{ time:   62.45, type: "jump",    nextIndex:  6, reference: "This day is a singer", fired: false },
					{ time:   68.00, type: "jump",    nextIndex:  7, reference: "This day is a painter", fired: false },
					{ time:   73.32, type: "jump",    nextIndex:  8, reference: "This day is a talker", fired: false },
					{ time:   80.00, type: "jump",    nextIndex:  9, reference: "Come down to earth", fired: false },
					{ time:   85.04, type: "jump",    nextIndex:  10, reference: "Your days are numbered (V2)", fired: false },
					{ time:   106.34, type: "jump",    nextIndex: 11, reference: "I don't know what the future holds (B1)", fired: false },
					{ time:   112.11, type: "jump",    nextIndex: 12, reference: "As into the winds of change (B1)", fired: false },
					{ time:   116.79, type: "jump",    nextIndex: 13, reference: "But traces and faces (B1)", fired: false },
					{ time:   122.34, type: "jump",    nextIndex: 14, reference: "And I know that they were living (B1)", fired: false },
					{ time:   127.88, type: "jump",    nextIndex: 15, reference: "I know that they were living (B1)", fired: false },
					{ time:   142.37, type: "jump",    nextIndex: 16, reference: "This moment is a sleeping child", fired: false },
					{ time:   147.70, type: "jump",    nextIndex: 17, reference: "This moment is a lost highway", fired: false },
					{ time:   153.03, type: "jump",    nextIndex: 18, reference: "This moment is a hurricane", fired: false },
					{ time:   159.57, type: "jump",    nextIndex: 19, reference: "There's no place left to run", fired: false },
					{ time:   164.96, type: "jump",    nextIndex: 20, reference: "Your one brief shining moment (V3)", fired: false },
					{ time:   188.41, type: "jump",    nextIndex: 21, reference: "I don't know what the future holds (B2)", fired: false },
					{ time:   194.16, type: "jump",    nextIndex: 22, reference: "As into the winds of change (B2)", fired: false },
					{ time:   199.15, type: "jump",    nextIndex: 23, reference: "But traces and faces (B2)", fired: false },
					{ time:   204.60, type: "jump",    nextIndex: 24, reference: "And I hope that we are living (B2)", fired: false },
					{ time:   210.21, type: "jump",    nextIndex: 25, reference: "I hope that we are living (B2)", fired: false },
					{ time:   243.39, type: "Y1pause", nextIndex: 26, reference: "song ends", fired: false }
				],
			},
			//	Up on Cripple Creek ISRB appoiintments		
			"upOnCrippleCreek": {
				base: "upOnCrippleCreek",
				display: "Up On Cripple Creek",
				bouncesPerLine: 16,
				bounceDuration: 1.0,
				background: "background.jpg",
				fontSize: 34,
				font: "Consolas",
				lyricsFile: "upOnCrippleCreek.lyric",
				chords: "upOnCrippleCreekChords_v1.jpg",
				credits: `Up On Cripple Creek\nWritten by Robbie Robertson as played by the ISRB`,
				appointments: [
					{ time:   0.00, type: "jump",    nextIndex:  0, reference: "Jaw Harp solo", fired: false },
					{ time:   54.91, type: "jump",    nextIndex:  1, reference: "When I get off of this mountain", fired: false },
					{ time:   57.28, type: "jump",    nextIndex:  2, reference: "You know where I'm gonna go", fired: false },
					{ time:   60.52, type: "jump",    nextIndex:  3, reference: "Straight down the Mississippi River", fired: false },
					{ time:   62.56, type: "jump",    nextIndex:  4, reference: "To the Gulf of Mexico", fired: false },
					{ time:   65.73, type: "jump",    nextIndex:  5, reference: "To Lake Charles, Louisiana", fired: false },
					{ time:   67.84, type: "jump",    nextIndex:  6, reference: "To a Bessie girl I once knew", fired: false },
					{ time:   71.54, type: "jump",    nextIndex:  7, reference: "She told me just to come on by", fired: false },
					{ time:   73.65, type: "jump",    nextIndex:  8, reference: "If there's anything she could do", fired: false },
					{ time:   76.55, type: "jump",    nextIndex:  9, reference: "Up on Cripple Creek, she sends me", fired: false },
					{ time:   79.19, type: "jump",    nextIndex:  10, reference: "If I spring a leak, she mends me", fired: false },
					{ time:   81.83, type: "jump",    nextIndex: 11, reference: "I don't have to speak, she defends me", fired: false },
					{ time:   84.73, type: "jump",    nextIndex: 12, reference: "A drunkard's dream if I ever did see one", fired: false },
					{ time:   87.64, type: "jump",    nextIndex: 13, reference: "riff", fired: false },
					{ time:   98.46, type: "jump",    nextIndex: 14, reference: "Good luck had just stung me", fired: false },
					{ time:   100.79, type: "jump",    nextIndex: 15, reference: "To the race track I did go", fired: false },
					{ time:   104.00, type: "jump",    nextIndex: 16, reference: "She bet on one horse to win", fired: false },
					{ time:   106.12, type: "jump",    nextIndex: 17, reference: "And I bet on another to show", fired: false },
					{ time:   109.02, type: "jump",    nextIndex: 18, reference: "The odds were in my favor", fired: false },
					{ time:   111.66, type: "jump",    nextIndex: 19, reference: "I had 'em five to one", fired: false },
					{ time:   115.09, type: "jump",    nextIndex: 20, reference: "That nag to win came around the track", fired: false },
					{ time:   117.46, type: "jump",    nextIndex: 21, reference: "Sure enough, we had won", fired: false },
					{ time:   120.00, type: "jump",    nextIndex: 22, reference: "Up on Cripple Creek, she sends me", fired: false },
					{ time:   122.90, type: "jump",    nextIndex: 23, reference: "If I spring a leak, she mends me", fired: false },
					{ time:   125.65, type: "jump",    nextIndex: 24, reference: "I don't have to speak, she defends me", fired: false },
					{ time:   128.29, type: "jump",    nextIndex: 25, reference: "A drunkard's dream if I ever did see one", fired: false },
					{ time:   139.47, type: "jump",    nextIndex: 26, reference: "Picked up all of my winnings", fired: false },
					{ time:   141.75, type: "jump",    nextIndex: 27, reference: "And I gave my little Bessie half", fired: false },
					{ time:   144.92, type: "jump",    nextIndex: 28, reference: "She tore it up and threw it in my face", fired: false },
					{ time:   147.56, type: "jump",    nextIndex: 29, reference: "Just for a laugh", fired: false },
					{ time:   150.20, type: "jump",    nextIndex: 30, reference: "Now there's one thing in the whole wide world", fired: false },
					{ time:   152.84, type: "jump",    nextIndex: 31, reference: "I sure would like to see", fired: false },
					{ time:   155.74, type: "jump",    nextIndex: 32, reference: "That's when that little love of mine", fired: false },
					{ time:   157.89, type: "jump",    nextIndex: 33, reference: "Dips her doughnut in my tea", fired: false },
					{ time:   161.02, type: "jump",    nextIndex: 34, reference: "Up on Cripple Creek, she sends me", fired: false },
					{ time:   163.92, type: "jump",    nextIndex: 35, reference: "If I spring a leak, she mends me", fired: false },
					{ time:   166.56, type: "jump",    nextIndex: 36, reference: "I don't have to speak, she defends me", fired: false },
					{ time:   169.21, type: "jump",    nextIndex: 37, reference: "A drunkard's dream if I ever did see one", fired: false },
					{ time:   187.68, type: "jump",    nextIndex: 38, reference: "Now me and my mate were back at the shack", fired: false },
					{ time:   190.32, type: "jump",    nextIndex: 39, reference: "We had Spike Jones on the box", fired: false },
					{ time:   193.49, type: "jump",    nextIndex: 40, reference: "She said I can't take the way he sings", fired: false },
					{ time:   195.60, type: "jump",    nextIndex: 41, reference: "But I love to hear him talk", fired: false },
					{ time:   198.94, type: "jump",    nextIndex: 42, reference: "Now that just gave my heart a throb", fired: false },
					{ time:   201.14, type: "jump",    nextIndex: 43, reference: "To the bottom of my feet", fired: false },
					{ time:   204.31, type: "jump",    nextIndex: 44, reference: "And I swore as I took another pull", fired: false },
					{ time:   206.69, type: "jump",    nextIndex: 45, reference: "My Bessie can't be beat", fired: false },
					{ time:   209.74, type: "jump",    nextIndex: 46, reference: "Up on Cripple Creek, she sends me", fired: false },
					{ time:   212.23, type: "jump",    nextIndex: 47, reference: "If I spring a leak, she mends me", fired: false },
					{ time:   215.13, type: "jump",    nextIndex: 48, reference: "I don't have to speak, she defends me", fired: false },
					{ time:   217.77, type: "jump",    nextIndex: 49, reference: "A drunkard's dream if I ever did see one", fired: false },
					{ time:   233.61, type: "jump",    nextIndex: 50, reference: "Well it's hot out in California", fired: false },
					{ time:   236.25, type: "jump",    nextIndex: 51, reference: "And up north it's freezing cold", fired: false },
					{ time:   239.74, type: "jump",    nextIndex: 52, reference: "And this living on the road is getting pretty old", fired: false },
					{ time:   244.17, type: "jump",    nextIndex: 53, reference: "So I guess I'll call up my big mama", fired: false },
					{ time:   247.07, type: "jump",    nextIndex: 54, reference: "Tell her I'll be rolling in", fired: false },
					{ time:   250.00, type: "jump",    nextIndex: 55, reference: "But you know deep down, I'm kind of tempted", fired: false },
					{ time:   252.88, type: "jump",    nextIndex: 56, reference: "To go and see my Bessie again", fired: false },
					{ time:   256.05, type: "jump",    nextIndex: 57, reference: "Up on Cripple Creek, she sends me", fired: false },
					{ time:   258.68, type: "jump",    nextIndex: 58, reference: "If I spring a leak, she mends me", fired: false },
					{ time:   261.32, type: "jump",    nextIndex: 59, reference: "I don't have to speak, she defends me", fired: false },
					{ time:   264.23, type: "jump",    nextIndex: 60, reference: "A drunkard's dream if I ever did see one", fired: false },
					{ time:   270.00, type: "jump",    nextIndex: 61, reference: "No-no, hu-hu", fired: false },
					{ time:   272.42, type: "jump",    nextIndex: 62, reference: "Lodl-lodl-lodl-uh-hu", fired: false },
					{ time:   275.58, type: "jump",    nextIndex: 63, reference: "No-no-hu", fired: false },
					{ time:   278.00, type: "jump",    nextIndex: 64, reference: "Lodl-lodl-lodl-uh-hu", fired: false },
					{ time:   280.42, type: "jump",    nextIndex: 65, reference: "No-no-hu", fired: false },
					{ time:   281.16, type: "jump",    nextIndex: 66, reference: "Lodl-lodl-lodl-uh-hu", fired: false },
					{ time:   282.82, type: "jump",    nextIndex: 67, reference: "No-no-hu", fired: false },
					{ time:   285.58, type: "jump",    nextIndex: 68, reference: "Lodl-lodl-lodl-uh-hu", fired: false },
					{ time:   303.82, type: "Y1pause", nextIndex: 69, reference: "song ends", fired: false }
				]
			},
		};